version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./:/app:ro
      - ./docker/nginx/nginx.main.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/logs:/var/log/nginx/
    ports:
      - 8100:80
    #      - 443:443
    restart: always
    stop_grace_period: 30s
    logging: &logging
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    links:
      - php
      - db:bd_network
    depends_on:
      - php
      - db
    networks:
      - app-network
  php:
    image: gitlab.icerockdev.com:4567/docker/php-7.4/dev-alpine-3.11:latest
    user: "0:0"
    environment:
      PHP_ENV: Development
        - PMA_ARBITRARY=1
        - PMA_HOST=db
    volumes:
      - ./:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/php/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini:ro
      - ./docker/php/www.conf.ini:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    stop_grace_period: 30s
    #    entrypoint: ['sh', '/app/docker/run/entrypoint.sh']
    command: 'php-fpm'
    logging: *logging
    links:
      - db:bd_network
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
#    command: "--default-authentication-plugin=mysql_native_password"
#    command: --innodb_use_native_aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Polyclinics
      - MYSQL_USER=Polyclinics
      - MYSQL_PASSWORD=!secret
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
